src/Fugitive4.Web/Controllers/DriverLicenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using AutoMapper;
using Fugitive4.Web.Extensions;
using Fugitive4.Services.Models;
using Fugitive4.Services.Services;
using Fugitive4.Web.Controllers.Bases;
using Fugitive4.Web.ViewModels.DriverLicense;
using Microsoft.AspNet.Authorization;

namespace Fugitive4.Web.Controllers
{
    [Authorize(Roles = "Member,Admin")]
    public class DriverLicenseController : ControllerBase
    {
	    private readonly IMapper _mapper;
		private readonly IDriverLicenseService _driverLicenseService;					
		private readonly ISubjectService _subjectService;

		public DriverLicenseController(IDriverLicenseService driverLicenseService,
								ISubjectService subjectService
,
								IMapper mapper		)
        {
            _driverLicenseService = driverLicenseService;
			_mapper = mapper;
			_subjectService = subjectService;

        }
[Route("Subject/{subjectId}/DriverLicense/Index")]
        public async Task<IActionResult> Index(int subjectId , string searchCriteria = null)
        {
			ViewBag.Title = "Index";
			ViewBag.TestValue = "Index";

            var driverLicenses = await _driverLicenseService.GetAllAsync();
            var driverLicenseList = new DriverLicenseListVm
            {
                DriverLicenses = _mapper.Map<IEnumerable<DriverLicense>, IEnumerable<DriverLicenseVm>>(driverLicenses.Where(s=>s.SubjectId==subjectId).ToList())
            };

            return View("Index", driverLicenseList);
        }

		public async Task<IActionResult> Details(int? id)
        {
			ViewBag.TestValue = "Details";
            if (id == null)
            {
                return HttpNotFound();
            }

            DriverLicense driverLicense = await _driverLicenseService.GetByIdAsync(id.Value);
            if (driverLicense == null)
            {
                return HttpNotFound();
            }

            var driverLicenseVm = _mapper.Map<DriverLicense, DriverLicenseVm>(driverLicense);

            return View(driverLicenseVm);
        }


[Route("Subject/{subjectId}/DriverLicense/Create", Name= "DriverLicenseForSubject")]
		public ActionResult Create(int subjectId, string returnUrl = "")
        {
			ViewBag.Title = "Create"; 
			ViewBag.TestValue = "Create";
            ViewBag.ReturnUrl = returnUrl;

            var driverLicenseVm = new DriverLicenseVm {SubjectId = subjectId};

			LoadLookups(driverLicenseVm);

            return View(driverLicenseVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
[Route("Subject/{subjectId}/DriverLicense/Create")]
        public async Task<IActionResult> Create(DriverLicenseVm driverLicenseVm, string returnUrl = "")
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var driverLicense = _mapper.Map<DriverLicenseVm, DriverLicense>(driverLicenseVm);
                    await _driverLicenseService.InsertAsync(driverLicense, GetLogonUser());
                    return RedirectToIndexOrSubjectDetail(returnUrl); //RedirectToAction("Index");
                }
				else
				{
                    var message = string.Join(" | ", ModelState.Values
                        .SelectMany(v => v.Errors)
                        .Select(e => e.ErrorMessage));
                    throw new Exception(message);
                }               
            }
            catch(Exception ex)
            {
				LogError(ex);
				//Add any dropdown values back to the VM Here
				LoadLookups(driverLicenseVm);

                return View(driverLicenseVm);
            }
        }

        [Route("Subject/{subjectId}/DriverLicense/Edit/{id}", Name = "DriverLicenseForSubjectEdit")]
		public async Task<IActionResult> Edit(int subjectId , int? id, string returnUrl = "")
        {
			ViewBag.Title = "Edit"; 
			ViewBag.TestValue = "Edit";
            ViewBag.ReturnUrl = returnUrl;

            if (id == null)
            {
                return HttpNotFound();
            }

            var driverLicense = await _driverLicenseService.GetByIdAsync(id.Value);
            if (driverLicense == null)
            {
                return HttpNotFound();
            }            
			
			var driverLicenseVm = _mapper.Map<DriverLicense, DriverLicenseVm>(driverLicense);

			LoadLookups(driverLicenseVm);

            return View(driverLicenseVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Subject/{subjectId}/DriverLicense/Edit/{id}", Name = "DriverLicenseForSubjectEdit")]
        public async Task<IActionResult> Edit(DriverLicenseVm driverLicenseVm, string returnUrl = "")
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var driverLicense = _mapper.Map<DriverLicenseVm, DriverLicense>(driverLicenseVm); 
                    await _driverLicenseService.UpdateAsync(driverLicense, GetLogonUser());
                    return RedirectToIndexOrSubjectDetail(returnUrl);
                }
				else
				{
                    var message = string.Join(" | ", ModelState.Values
                        .SelectMany(v => v.Errors)
                        .Select(e => e.ErrorMessage));
                    throw new Exception(message);
                }                 
            }
            catch(Exception ex)
            {
				LogError(ex);
				//Add any dropdown values back to the VM Here
				LoadLookups(driverLicenseVm);

                return View(driverLicenseVm);
            }
        }

		[ActionName("Delete")]
[Route("Subject/{subjectId}/DriverLicense/Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
			ViewBag.Title = "Delete";
			ViewBag.TestValue = "Delete"; 

			if (id == null)
            {
                return HttpNotFound();
            }

            var driverLicense = await _driverLicenseService.GetByIdAsync(id.Value);
			if (driverLicense == null)
            {
                return HttpNotFound();
            }

            var driverLicenseVm = _mapper.Map<DriverLicense, DriverLicenseVm>(driverLicense);

            return View(driverLicenseVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
[Route("Subject/{subjectId}/DriverLicense/Delete/{id}")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _driverLicenseService.DeleteAsync(id, GetLogonUser());
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

		private void LoadLookups(DriverLicenseVm driverLicenseVm)
        {
			driverLicenseVm.SubjectList = _subjectService.GetAll(GetLogonUser()).ToSelectList(s => s.Id.ToString(), s => s.EyeColor).ToList();
		}

	}
}

src/Fugitive4.Web/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using AutoMapper;
using Fugitive4.Services.Enums;
using Fugitive4.Web.Extensions;
using Fugitive4.Services.Models;
using Fugitive4.Services.Services;
using Fugitive4.Web.Controllers.Bases;
using Fugitive4.Web.ViewModels.ActivityNote;
using Fugitive4.Web.ViewModels.BailBond;
using Fugitive4.Web.ViewModels.Subject;
using Microsoft.AspNet.Authorization;
using Fugitive4.Web.ViewModels.SubjectRelationship;
using Fugitive4.Web.ViewModels.Address;
using Fugitive4.Web.ViewModels.StoredFile;
using Fugitive4.Web.ViewModels._Interfaces;

namespace Fugitive4.Web.Controllers
{
    [Authorize(Roles = "Member,Admin")]
    public class SubjectController : ControllerBase
    {
	    private readonly IMapper _mapper; 

		private readonly ISubjectService _subjectService;					
		private readonly IReferrerService _referrerService;					
		private readonly IGenderService _genderService;					
		private readonly IRaceService _raceService;
	    private readonly ISubjectRelationshipService _subjectRelationshipService;
	    private readonly IRelationshipTypeService _relationshipTypeService;
	    private readonly IAddressService _addressService;
	    private readonly IStoredFileService _storedFileService;
	    private readonly IBookingChargeService _bookingChargeService;
	    private readonly IEmployerService _employerService;

	    public SubjectController(ISubjectService subjectService,
								IReferrerService referrerService,
								IGenderService genderService,
								IRaceService raceService,
                                ISubjectRelationshipService subjectRelationshipService,
                                IRelationshipTypeService relationshipTypeService,
                                IAddressService addressService,
                                IStoredFileService storedFileService,
                                IBookingChargeService bookingChargeService,
                                IEmployerService employerService,
								IMapper mapper		)
        {
            _subjectService = subjectService;
			_mapper = mapper;
			_referrerService = referrerService;
			_genderService = genderService;
			_raceService = raceService;
	        _subjectRelationshipService = subjectRelationshipService;
	        _relationshipTypeService = relationshipTypeService;
	        _addressService = addressService;
	        _storedFileService = storedFileService;
	        _bookingChargeService = bookingChargeService;
	        _employerService = employerService;
        }


        public async Task<IActionResult> Search()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search(SubjectSearchVm subjectSearchVm)
        {
            return RedirectToAction(actionName: "Index", routeValues: new { searchCriteria = subjectSearchVm.SearchCriteria });
        }

        [Route("Subject/Index", Name="SubjectIndex")]
        public async Task<IActionResult> Index( string searchCriteria = null, int? bailBondId = null, int? employerId = null)
        {
			ViewBag.Title = "Index";
			ViewBag.TestValue = "Index";

            var subjects = (await _subjectService.GetAllAsync(GetLogonUser())).ToList();


            if (!string.IsNullOrWhiteSpace(searchCriteria))
            {
                var search = searchCriteria.Split();
                var subjectFilter = subjects.Where(a => search.All(
                s => (a.Lastname ?? "").ToLower().Contains(s.ToLower()) ||
                (a.Firstname ?? "").ToLower().Contains(s.ToLower()) ||
                (a.Middlename ?? "").ToLower().Contains(s.ToLower())
                ));
                subjects = (subjectFilter == null ? new List<Subject>() : subjectFilter.ToList());
            }
            else if(bailBondId.HasValue && bailBondId.Value > 0)
            {
                subjects = subjects.Where(s => s.SubjectRelationships != null && s.SubjectRelationships.Any(sr => sr.BailBondId == bailBondId.Value)).ToList();
            }
            else if (employerId.HasValue && employerId.Value > 0)
            {
                subjects = subjects.Where(s => s.SubjectRelationships != null && s.SubjectRelationships.Any(sr => sr.EmployerId == employerId.Value)).ToList();
            }
            else
            {

                var newSubjects =
                    subjects
                        .Where(s => !s.BailBonds.Any())
                        .Where( s=> !s.SubjectRelationships.Any())
                        .Where(s=> !s.OtherSubjectRelationships.Any())
                        .ToList();


                subjects = subjects
                    .Where(s => 
                                (s.BailBonds.Any(b => b.DefaultDate >= DateTime.Now && (b.Done.HasValue == false || (b.Done.HasValue && b.Done.Value == false)))) 
                          )
                    .OrderBy(s=>s.BailBonds
                    .OrderBy(t => t.DefaultDate)
                    .First()
                    .DefaultDate)
                    .ToList();

                try
                {
                    if (newSubjects.Any())
                    {
                        subjects.AddRange(newSubjects.ToList());
                    }
                }
                catch (Exception ex)
                {
                    
                }

            }
            
            var subjectvms = _mapper.Map<IEnumerable<Subject>, IEnumerable<SubjectVm>>(subjects.ToList());
            foreach (var subject in subjectvms)
            {
                subject.CurrentBond = subject
                .BailBonds
                .OrderBy(t => t.DefaultDate)
                .FirstOrDefault(b => b.DefaultDate > DateTime.Now);
            }

            var subjectList = new SubjectListVm
            {
                Subjects = subjectvms
            };

            return View("Index", subjectList);
        }
        public async Task<IActionResult> Geomap(int? id)
        {
            //Add urls to each of the addresses and locations, to link to the item in the software
            if (id == null)
            {
                return HttpNotFound();
            }

            Subject subject = await _subjectService.GetByIdAllAsync(id.Value, GetLogonUser());
            if (subject == null)
            {
                return HttpNotFound();
            }

            var subjectRelationships = _subjectRelationshipService.GetBySubjectId(id.Value).ToList();

            var geoMapVm = new GeoMapVm
            {
                Addresses = new List<SubjectMapAddressVm>(),
                Locations = new List<SubjectMapLatLongVm>()
            };

            foreach (IAddress address in subject.Addresses)
            {
                var subjectMapAddressVm = new SubjectMapAddressVm();
                subjectMapAddressVm.Name = "Subject ";
                subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", address.Address1, address.City, address.State, address.Zipcode);
                subjectMapAddressVm.Icon = "house";
                geoMapVm.Addresses.Add(subjectMapAddressVm);
            }

            foreach (var subjectRelationship in subjectRelationships)
            {
                var otherPerson = subjectRelationship.Subject.Id == subject.Id ? subjectRelationship.RelatedSubject : subjectRelationship.Subject;
                foreach (IAddress address in otherPerson.Addresses)
                {
                    var subjectMapAddressVm = new SubjectMapAddressVm();
                    subjectMapAddressVm.Name =String.Format("Related Subject - {0},{1}", otherPerson.Lastname,otherPerson.Firstname);
                    subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", address.Address1, address.City, address.State, address.Zipcode);
                    subjectMapAddressVm.Icon = "friend";
                    geoMapVm.Addresses.Add(subjectMapAddressVm);
                }
            }

            foreach(var bailBond in subject.BailBonds)
            {
                foreach(var charge in bailBond.BookingCharges)
                {
                    IAddress chargeAddress = charge as IAddress;
                    var subjectMapAddressVm = new SubjectMapAddressVm();
                    subjectMapAddressVm.Name = String.Format("Bond - {0},{1}", charge.ChargeName, charge.CodeNumber);
                    subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", chargeAddress.Address1, chargeAddress.City, chargeAddress.State, chargeAddress.Zipcode);
                    subjectMapAddressVm.Icon = "handcuffs";
                    geoMapVm.Addresses.Add(subjectMapAddressVm);
                }
            }

            foreach(var employer in subject.Employers)
            {
                IAddress employerAddress = employer as IAddress;
                var subjectMapAddressVm = new SubjectMapAddressVm();
                subjectMapAddressVm.Name = String.Format("Employer - {0}", employer.Name);
                subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", employerAddress.Address1, employerAddress.City, employerAddress.State, employerAddress.Zipcode);
                subjectMapAddressVm.Icon = "office";
                geoMapVm.Addresses.Add(subjectMapAddressVm);
            }

            foreach (var location in subject.ActivityNotes)
            {
                var subjectMapLatLongVm = new SubjectMapLatLongVm();
                subjectMapLatLongVm.Name = "Activity Note" + location.ActivityDate.ToString("M/d/yy h:m tt");
                subjectMapLatLongVm.Latitude = location.Latitude;
                subjectMapLatLongVm.Longitude = location.Longitude;
                subjectMapLatLongVm.Icon = "car";

src/Fugitive4.Web/Views/DriverLicense/Create.cshtml
@using Fugitive4.Web.Helpers;
@model Fugitive4.Web.ViewModels.DriverLicense.DriverLicenseVm

@{
    ViewBag.Title = "Create DriverLicense";
}

<form asp-action="Create" asp-route-returnUrl="@ViewBag.ReturnUrl">    
	<div class="form-horizontal">
		<div class="row title-row">
			<h1 class="pull-left">@ViewBag.Title</h1>

			<div class="button-container pull-right h1-row text-right">
				<a asp-controller="DriverLicense" asp-action="Index">Cancel</a>
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>

<div class="content-wrapper">
	<div class="panel panel-default">
        <div class="panel-body">
            <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <input type="hidden" asp-for="SubjectId" />
            <div class="row"><!-- Start .row 1-->
                <div class="form-group col-md-12">
                    <label asp-for="DLNumber" class="control-label"></label>
                    <input asp-for="DLNumber" class="form-control" />
                    <span asp-validation-for="DLNumber" class="text-danger" />
                </div>
            </div><!-- END .row 1-->
            <div class="row">
                <!-- Start .row 2-->
                <div class="form-group col-md-3">
                    <label asp-for="Address1" class="control-label"></label>
                    <input asp-for="Address1" class="form-control" />
                    <span asp-validation-for="Address1" class="text-danger" />
                </div>
                <div class="form-group col-md-9">
                    <label asp-for="Address2" class="control-label"></label>
                    <input asp-for="Address2" class="form-control" />
                    <span asp-validation-for="Address2" class="text-danger" />
                </div>
                
            </div><!-- END .row 2-->
            <div class="row">
                <!-- Start .row 3-->
                <div class="form-group col-md-3">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger" />
                </div>
                <div class="form-group col-md-1">
                    <label asp-for="State" class="control-label"></label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger" />
                </div>
                <div class="form-group col-md-8">
                    <label asp-for="Zipcode" class="control-label"></label>
                    <input asp-for="Zipcode" class="form-control" />
                    <span asp-validation-for="Zipcode" class="text-danger" />
                </div>
            </div><!-- END .row 3-->
            <div class="row">
                <!-- Start .row 4-->
                <div class="form-group col-md-12">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger" />
                </div>
            </div><!-- END .row 4-->
            <div class="row">
                <!-- Start .row 5-->
                <div class="form-group col-md-4">
                    <label asp-for="IssuingState" class="control-label"></label>
                    <input asp-for="IssuingState" class="form-control" />
                    <span asp-validation-for="IssuingState" class="text-danger" />
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="IssueDate" class="control-label"></label>
                    <input asp-for="IssueDate" class="form-control" />
                    <span asp-validation-for="IssueDate" class="text-danger" />
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="ExpirationDate" class="control-label"></label>
                    <input asp-for="ExpirationDate" class="form-control" />
                    <span asp-validation-for="ExpirationDate" class="text-danger" />
                </div>
            </div><!-- END .row 5-->
            <div class="row">
                <!-- Start .row 6-->
                <div class="form-group col-md-12">
                    <label asp-for="Notes" class="control-label"></label>
                    <textarea asp-for="Notes" class="form-control"></textarea>
                    <span asp-validation-for="Notes" class="text-danger" />
                </div>
            </div><!-- END .row 6-->
        </div>
	</div>
</div>
<!-- END .content-wrapper -->

        <div class="form-group">
            <div class="col-md-offset-2 ">
				<a href="@LinkHelper.GetIndexOrReturnDetail(Context, ViewBag.ReturnUrl)">Cancel</a>
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Fugitive4.Web/Views/DriverLicense/Edit.cshtml
@model Fugitive4.Web.ViewModels.DriverLicense.DriverLicenseVm

@{
    ViewBag.Title = "Edit DriverLicense";
}

<form asp-action="Edit" asp-route-returnUrl="@ViewBag.ReturnUrl">    
	<div class="form-horizontal">
		<div class="row title-row">
			<h1 class="pull-left">@ViewBag.Title</h1>

			<div class="button-container pull-right h1-row text-right">
				<a asp-controller="DriverLicense" asp-action="Index">Cancel</a>
				<input type="submit" value="Edit" class="btn btn-default" />
			</div>
		</div>

<div class="content-wrapper">
	<div class="panel panel-default">
		<div class="panel-body">
			<div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id"/>
            <input type="hidden" asp-for="SubjectId" />
            <div class="row">
                <!-- Start .row 1-->
                <div class="form-group col-md-12">
                    <label asp-for="DLNumber" class="control-label"></label>
                    <input asp-for="DLNumber" class="form-control" />
                    <span asp-validation-for="DLNumber" class="text-danger" />
                </div>
            </div><!-- END .row 1-->
            <div class="row">
                <!-- Start .row 2-->
                <div class="form-group col-md-3">
                    <label asp-for="Address1" class="control-label"></label>
                    <input asp-for="Address1" class="form-control" />
                    <span asp-validation-for="Address1" class="text-danger" />
                </div>
                <div class="form-group col-md-9">
                    <label asp-for="Address2" class="control-label"></label>
                    <input asp-for="Address2" class="form-control" />
                    <span asp-validation-for="Address2" class="text-danger" />
                </div>

            </div><!-- END .row 2-->
            <div class="row">
                <!-- Start .row 3-->
                <div class="form-group col-md-3">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger" />
                </div>
                <div class="form-group col-md-1">
                    <label asp-for="State" class="control-label"></label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger" />
                </div>
                <div class="form-group col-md-8">
                    <label asp-for="Zipcode" class="control-label"></label>
                    <input asp-for="Zipcode" class="form-control" />
                    <span asp-validation-for="Zipcode" class="text-danger" />
                </div>
            </div><!-- END .row 3-->
            <div class="row">
                <!-- Start .row 4-->
                <div class="form-group col-md-12">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger" />
                </div>
            </div><!-- END .row 4-->
            <div class="row">
                <!-- Start .row 5-->
                <div class="form-group col-md-4">
                    <label asp-for="IssuingState" class="control-label"></label>
                    <input asp-for="IssuingState" class="form-control" />
                    <span asp-validation-for="IssuingState" class="text-danger" />
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="IssueDate" class="control-label"></label>
                    <input asp-for="IssueDate" class="form-control" />
                    <span asp-validation-for="IssueDate" class="text-danger" />
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="ExpirationDate" class="control-label"></label>
                    <input asp-for="ExpirationDate" class="form-control" />
                    <span asp-validation-for="ExpirationDate" class="text-danger" />
                </div>
            </div><!-- END .row 5-->
            <div class="row">
                <!-- Start .row 6-->
                <div class="form-group col-md-12">
                    <label asp-for="Notes" class="control-label"></label>
                    <textarea asp-for="Notes" class="form-control"></textarea>
                    <span asp-validation-for="Notes" class="text-danger" />
                </div>
            </div><!-- END .row 6-->
		</div>
	</div>
</div>
<!-- END .content-wrapper -->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
				<a asp-controller="DriverLicense" asp-action="Index">Cancel</a>
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Fugitive4.Web/Views/DriverLicense/Index.cshtml
@model Fugitive4.Web.ViewModels.DriverLicense.DriverLicenseListVm

@{
    ViewBag.Title = "Manage DriverLicense";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="panel panel-default">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>
					@Html.DisplayNameFor(model => model.DriverLicenses.FirstOrDefault().DLNumber)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.DriverLicenses.FirstOrDefault().FullName)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.DriverLicenses.FirstOrDefault().IssuingState)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.DriverLicenses.FirstOrDefault().Notes)
				</th>

				<th></th>	
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.DriverLicenses) 
			{
			<tr>

				<td>
					@Html.DisplayFor(modelItem => item.DLNumber)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.FullName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.IssuingState)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Notes)
				</td>

       <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
			</tr>
			}
		</tbody>
	</table>
</div>

<div class=" footer-button-row">
	<div class="button-container text-right">
		@Html.ActionLink("Back to Subjects", "Index", "Subject", null, new {@class="pull-left"})
		<a asp-action="Create">Create New</a>
	</div>
</div>