src/Fugitive4.Web/Controllers/AKAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using AutoMapper;
using Fugitive4.Web.Extensions;
using Fugitive4.Services.Models;
using Fugitive4.Services.Services;
using Fugitive4.Web.Controllers.Bases;
using Fugitive4.Web.ViewModels.AKA;
using Microsoft.AspNet.Authorization;

namespace Fugitive4.Web.Controllers
{
    [Authorize(Roles = "Member,Admin")]
    public class AKAController : ControllerBase
    {
	    private readonly IMapper _mapper;
		private readonly IAKAService _aKAService;					
		private readonly ISubjectService _subjectService;

		public AKAController(IAKAService aKAService,
								ISubjectService subjectService
,
								IMapper mapper		)
        {
            _aKAService = aKAService;
			_mapper = mapper;
			_subjectService = subjectService;

        }
		[Route("Subject/{subjectId}/AKA/Index")]
        public async Task<IActionResult> Index(int subjectId , string searchCriteria = null)
        {
			ViewBag.Title = "Index";
			ViewBag.TestValue = "Index";

            var aKAS = await _aKAService.GetAllAsync();
            var aKAList = new AKAListVm
            {
                AKAS = _mapper.Map<IEnumerable<AKA>, IEnumerable<AKAVm>>(aKAS.ToList())
            };

            return View("Index", aKAList);
        }

		public async Task<IActionResult> Details(int? id)
        {
			ViewBag.TestValue = "Details";
            if (id == null)
            {
                return HttpNotFound();
            }

            AKA aKA = await _aKAService.GetByIdAsync(id.Value);
            if (aKA == null)
            {
                return HttpNotFound();
            }

            var aKAVm = _mapper.Map<AKA, AKAVm>(aKA);

            return View(aKAVm);
        }


		[Route("Subject/{subjectId}/AKA/Create", Name="AKAForSubject")]
		public ActionResult Create(int subjectId , string returnUrl = "")
        {
			ViewBag.Title = "Create"; 
			ViewBag.TestValue = "Create";
			ViewBag.ReturnUrl = returnUrl;

            var aKAVm = new AKAVm();

			LoadLookups(aKAVm);

            return View(aKAVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
		[Route("Subject/{subjectId}/AKA/Create", Name = "AKAForSubject")]
        public async Task<IActionResult> Create(AKAVm aKAVm, string returnUrl = "")
        {
					ViewBag.ReturnUrl = returnUrl;
            try
            {
                if (ModelState.IsValid)
                {
                    var aKA = _mapper.Map<AKAVm, AKA>(aKAVm);
                    await _aKAService.InsertAsync(aKA, GetLogonUser());
					return RedirectToIndexOrSubjectDetail(returnUrl);
                }
				else
				{
                    var message = string.Join(" | ", ModelState.Values
                        .SelectMany(v => v.Errors)
                        .Select(e => e.ErrorMessage));
                    throw new Exception(message);
                }               
            }
            catch(Exception ex)
            {
				LogError(ex);
				//Add any dropdown values back to the VM Here
				LoadLookups(aKAVm);

                return View(aKAVm);
            }
        }

		[Route("Subject/{subjectId}/AKA/Edit/{id}", Name = "AKAForSubjectEdit")]
		public async Task<IActionResult> Edit(int subjectId , int? id, string returnUrl = "")
        {
			ViewBag.Title = "Edit"; 
			ViewBag.TestValue = "Edit";
			ViewBag.ReturnUrl = returnUrl;

			if (id == null)
            {
                return HttpNotFound();
            }

            var aKA = await _aKAService.GetByIdAsync(id.Value);
            if (aKA == null)
            {
                return HttpNotFound();
            }            
			
			var aKAVm = _mapper.Map<AKA, AKAVm>(aKA);

			LoadLookups(aKAVm);

            return View(aKAVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
		[Route("Subject/{subjectId}/AKA/Edit/{id}", Name = "AKAForSubjectEdit")]
        public async Task<IActionResult> Edit(AKAVm aKAVm, string returnUrl = "")
        {
			ViewBag.ReturnUrl = returnUrl;
            try
            {
                if (ModelState.IsValid)
                {
                    var aKA = _mapper.Map<AKAVm, AKA>(aKAVm); 
                    await _aKAService.UpdateAsync(aKA, GetLogonUser());
					return RedirectToIndexOrSubjectDetail(returnUrl);
                }
				else
				{
                    var message = string.Join(" | ", ModelState.Values
                        .SelectMany(v => v.Errors)
                        .Select(e => e.ErrorMessage));
                    throw new Exception(message);
                }                 
            }
            catch(Exception ex)
            {
				LogError(ex);
				//Add any dropdown values back to the VM Here
				LoadLookups(aKAVm);

                return View(aKAVm);
            }
        }

		[ActionName("Delete")]
		[Route("Subject/{subjectId}/AKA/Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
			ViewBag.Title = "Delete";
			ViewBag.TestValue = "Delete"; 

			if (id == null)
            {
                return HttpNotFound();
            }

            var aKA = await _aKAService.GetByIdAsync(id.Value);
			if (aKA == null)
            {
                return HttpNotFound();
            }

            var aKAVm = _mapper.Map<AKA, AKAVm>(aKA);

            return View(aKAVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
		[Route("Subject/{subjectId}/AKA/Delete/{id}")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _aKAService.DeleteAsync(id, GetLogonUser());
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

		private void LoadLookups(AKAVm aKAVm)
        {
			aKAVm.SubjectList = _subjectService.GetAll(GetLogonUser()).ToSelectList(s => s.Id.ToString(), s => s.EyeColor).ToList();
		}

	}
}

src/Fugitive4.Web/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using AutoMapper;
using Fugitive4.Services.Enums;
using Fugitive4.Web.Extensions;
using Fugitive4.Services.Models;
using Fugitive4.Services.Services;
using Fugitive4.Web.Controllers.Bases;
using Fugitive4.Web.ViewModels.ActivityNote;
using Fugitive4.Web.ViewModels.BailBond;
using Fugitive4.Web.ViewModels.Subject;
using Microsoft.AspNet.Authorization;
using Fugitive4.Web.ViewModels.SubjectRelationship;
using Fugitive4.Web.ViewModels.Address;
using Fugitive4.Web.ViewModels.StoredFile;
using Fugitive4.Web.ViewModels._Interfaces;

namespace Fugitive4.Web.Controllers
{
    [Authorize(Roles = "Member,Admin")]
    public class SubjectController : ControllerBase
    {
	    private readonly IMapper _mapper; 

		private readonly ISubjectService _subjectService;					
		private readonly IReferrerService _referrerService;					
		private readonly IGenderService _genderService;					
		private readonly IRaceService _raceService;
	    private readonly ISubjectRelationshipService _subjectRelationshipService;
	    private readonly IRelationshipTypeService _relationshipTypeService;
	    private readonly IAddressService _addressService;
	    private readonly IStoredFileService _storedFileService;
	    private readonly IBookingChargeService _bookingChargeService;
	    private readonly IEmployerService _employerService;

	    public SubjectController(ISubjectService subjectService,
								IReferrerService referrerService,
								IGenderService genderService,
								IRaceService raceService,
                                ISubjectRelationshipService subjectRelationshipService,
                                IRelationshipTypeService relationshipTypeService,
                                IAddressService addressService,
                                IStoredFileService storedFileService,
                                IBookingChargeService bookingChargeService,
                                IEmployerService employerService,
								IMapper mapper		)
        {
            _subjectService = subjectService;
			_mapper = mapper;
			_referrerService = referrerService;
			_genderService = genderService;
			_raceService = raceService;
	        _subjectRelationshipService = subjectRelationshipService;
	        _relationshipTypeService = relationshipTypeService;
	        _addressService = addressService;
	        _storedFileService = storedFileService;
	        _bookingChargeService = bookingChargeService;
	        _employerService = employerService;
        }


        public async Task<IActionResult> Search()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search(SubjectSearchVm subjectSearchVm)
        {
            return RedirectToAction(actionName: "Index", routeValues: new { searchCriteria = subjectSearchVm.SearchCriteria });
        }

        [Route("Subject/Index", Name="SubjectIndex")]
        public async Task<IActionResult> Index( string searchCriteria = null, int? bailBondId = null, int? employerId = null)
        {
			ViewBag.Title = "Index";
			ViewBag.TestValue = "Index";

            var subjects = (await _subjectService.GetAllAsync(GetLogonUser())).ToList();


            if (!string.IsNullOrWhiteSpace(searchCriteria))
            {
                var search = searchCriteria.Split();
                var subjectFilter = subjects.Where(a => search.All(
                s => (a.Lastname ?? "").ToLower().Contains(s.ToLower()) ||
                (a.Firstname ?? "").ToLower().Contains(s.ToLower()) ||
                (a.Middlename ?? "").ToLower().Contains(s.ToLower())
                ));
                subjects = (subjectFilter == null ? new List<Subject>() : subjectFilter.ToList());
            }
            else if(bailBondId.HasValue && bailBondId.Value > 0)
            {
                subjects = subjects.Where(s => s.SubjectRelationships != null && s.SubjectRelationships.Any(sr => sr.BailBondId == bailBondId.Value)).ToList();
            }
            else if (employerId.HasValue && employerId.Value > 0)
            {
                subjects = subjects.Where(s => s.SubjectRelationships != null && s.SubjectRelationships.Any(sr => sr.EmployerId == employerId.Value)).ToList();
            }
            else
            {

                var newSubjects =
                    subjects
                        .Where(s => !s.BailBonds.Any())
                        .Where( s=> !s.SubjectRelationships.Any())
                        .Where(s=> !s.OtherSubjectRelationships.Any())
                        .ToList();


                subjects = subjects
                    .Where(s => 
                                (s.BailBonds.Any(b => b.DefaultDate >= DateTime.Now && (b.Done.HasValue == false || (b.Done.HasValue && b.Done.Value == false)))) 
                          )
                    .OrderBy(s=>s.BailBonds
                    .OrderBy(t => t.DefaultDate)
                    .First()
                    .DefaultDate)
                    .ToList();

                try
                {
                    if (newSubjects.Any())
                    {
                        subjects.AddRange(newSubjects.ToList());
                    }
                }
                catch (Exception ex)
                {
                    
                }

            }
            
            var subjectvms = _mapper.Map<IEnumerable<Subject>, IEnumerable<SubjectVm>>(subjects.ToList());
            foreach (var subject in subjectvms)
            {
                subject.CurrentBond = subject
                .BailBonds
                .OrderBy(t => t.DefaultDate)
                .FirstOrDefault(b => b.DefaultDate > DateTime.Now);
            }

            var subjectList = new SubjectListVm
            {
                Subjects = subjectvms
            };

            return View("Index", subjectList);
        }
        public async Task<IActionResult> Geomap(int? id)
        {
            //Add urls to each of the addresses and locations, to link to the item in the software
            if (id == null)
            {
                return HttpNotFound();
            }

            Subject subject = await _subjectService.GetByIdAllAsync(id.Value, GetLogonUser());
            if (subject == null)
            {
                return HttpNotFound();
            }

            var subjectRelationships = _subjectRelationshipService.GetBySubjectId(id.Value).ToList();

            var geoMapVm = new GeoMapVm
            {
                Addresses = new List<SubjectMapAddressVm>(),
                Locations = new List<SubjectMapLatLongVm>()
            };

            foreach (IAddress address in subject.Addresses)
            {
                var subjectMapAddressVm = new SubjectMapAddressVm();
                subjectMapAddressVm.Name = "Subject ";
                subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", address.Address1, address.City, address.State, address.Zipcode);
                subjectMapAddressVm.Icon = "house";
                geoMapVm.Addresses.Add(subjectMapAddressVm);
            }

            foreach (var subjectRelationship in subjectRelationships)
            {
                var otherPerson = subjectRelationship.Subject.Id == subject.Id ? subjectRelationship.RelatedSubject : subjectRelationship.Subject;
                foreach (IAddress address in otherPerson.Addresses)
                {
                    var subjectMapAddressVm = new SubjectMapAddressVm();
                    subjectMapAddressVm.Name =String.Format("Related Subject - {0},{1}", otherPerson.Lastname,otherPerson.Firstname);
                    subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", address.Address1, address.City, address.State, address.Zipcode);
                    subjectMapAddressVm.Icon = "friend";
                    geoMapVm.Addresses.Add(subjectMapAddressVm);
                }
            }

            foreach(var bailBond in subject.BailBonds)
            {
                foreach(var charge in bailBond.BookingCharges)
                {
                    IAddress chargeAddress = charge as IAddress;
                    var subjectMapAddressVm = new SubjectMapAddressVm();
                    subjectMapAddressVm.Name = String.Format("Bond - {0},{1}", charge.ChargeName, charge.CodeNumber);
                    subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", chargeAddress.Address1, chargeAddress.City, chargeAddress.State, chargeAddress.Zipcode);
                    subjectMapAddressVm.Icon = "handcuffs";
                    geoMapVm.Addresses.Add(subjectMapAddressVm);
                }
            }

            foreach(var employer in subject.Employers)
            {
                IAddress employerAddress = employer as IAddress;
                var subjectMapAddressVm = new SubjectMapAddressVm();
                subjectMapAddressVm.Name = String.Format("Employer - {0}", employer.Name);
                subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", employerAddress.Address1, employerAddress.City, employerAddress.State, employerAddress.Zipcode);
                subjectMapAddressVm.Icon = "office";
                geoMapVm.Addresses.Add(subjectMapAddressVm);
            }

            foreach (var location in subject.ActivityNotes)
            {
                var subjectMapLatLongVm = new SubjectMapLatLongVm();
                subjectMapLatLongVm.Name = "Activity Note" + location.ActivityDate.ToString("M/d/yy h:m tt");
                subjectMapLatLongVm.Latitude = location.Latitude;
                subjectMapLatLongVm.Longitude = location.Longitude;
                subjectMapLatLongVm.Icon = "car";

src/Fugitive4.Web/Views/AKA/Create.cshtml
@using Fugitive4.Web.Helpers;
@model Fugitive4.Web.ViewModels.AKA.AKAVm

@{
    ViewBag.Title = "Create AKA";
}

<form asp-action="Create" asp-route-returnUrl="@ViewBag.ReturnUrl">    
	<div class="form-horizontal">
		<div class="row title-row">
			<h1 class="pull-left">@ViewBag.Title</h1>

			<div class="button-container pull-right h1-row text-right">
				<a asp-controller="AKA" asp-action="Index">Cancel</a>
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div> 

<div class="content-wrapper">
	<div class="panel panel-default">
		<div class="panel-body">
			<div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id"/>
				<div class="row">
					<div class="form-group col-md-12">
						<label asp-for="Firstname" class="control-label"></label>
						<input asp-for="Firstname" class="form-control"/>
					
						<span asp-validation-for="Firstname" class="text-danger" />
					</div>
				</div>
				<div class="row">
					<div class="form-group col-md-12">
						<label asp-for="Middlename" class="control-label"></label>
						<input asp-for="Middlename" class="form-control"/>
					
						<span asp-validation-for="Middlename" class="text-danger" />
					</div>
				</div>
				<div class="row">
					<div class="form-group col-md-12">
						<label asp-for="Lastname" class="control-label"></label>
						<input asp-for="Lastname" class="form-control"/>
					
						<span asp-validation-for="Lastname" class="text-danger" />
					</div>
				</div>
				<input type="hidden" asp-for="SubjectId" />

				<div class="row">
					<div class="form-group col-md-12">
				
						<input asp-for="Disabled"/>
						<label asp-for="Disabled" class="control-label"></label>
					
						<span asp-validation-for="Disabled" class="text-danger" />
					</div>
				</div>
				
		</div>
	</div>
</div>
<!-- END .content-wrapper -->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
				<a href="@LinkHelper.GetIndexOrReturnDetail(Context, ViewBag.ReturnUrl)">Cancel</a>
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Fugitive4.Web/Views/AKA/Delete.cshtml
@model Fugitive4.Web.ViewModels.AKA.AKAVm

@{
    ViewBag.Title = "Delete AKA";
}


<div class="row title-row">
	<h1 class="pull-left">@ViewBag.Title</h1>

	<div class="button-container pull-right h1-row text-right">
		<form asp-action="Delete">
			<div class="form-actions no-color">
				<input type="submit" value="Delete" class="btn btn-default" /> |
				<a asp-action="Index">Back to List</a>
			</div>
		</form>
	</div>
</div>

<div class="content-wrapper">

	<div class="panel panel-default">
		<div class="panel-body">

			<div class="alert alert-danger clearfix">
				<p class="pull-left">Are you sure you want to delete this AKA?</p>
			</div>
			<!-- END .alert -->

			<div>
				<dl class="section-spacing clearfix dl-inline-dd dl-inline-label-right">
 
					<dt>@Html.DisplayNameFor(model => model.Firstname)</dt>
					<dd>@Html.DisplayFor(model => model.Firstname)</dd>

					<dt>@Html.DisplayNameFor(model => model.Middlename)</dt>
					<dd>@Html.DisplayFor(model => model.Middlename)</dd>

					<dt>@Html.DisplayNameFor(model => model.Lastname)</dt>
					<dd>@Html.DisplayFor(model => model.Lastname)</dd>

					<dt>@Html.DisplayNameFor(model => model.SubjectId)</dt>
					<dd>@Html.DisplayFor(model => model.SubjectId)</dd>

					<dt>@Html.DisplayNameFor(model => model.Disabled)</dt>
					<dd>@Html.DisplayFor(model => model.Disabled)</dd>

				</dl>

				@Html.HiddenFor(model=>model.Id)
				@Html.HiddenFor(model=>model.Firstname)
				@Html.HiddenFor(model=>model.Middlename)
				@Html.HiddenFor(model=>model.Lastname)
				@Html.HiddenFor(model=>model.SubjectId)
				@Html.HiddenFor(model=>model.Disabled)
				@Html.HiddenFor(model=>model.CreatedBy)
				@Html.HiddenFor(model=>model.CreatedDate)
				@Html.HiddenFor(model=>model.ModifiedBy)
				@Html.HiddenFor(model=>model.ModifiedDate)
				<div class="button-container top-hr text-right">    
					<form asp-action="Delete">
						<div class="form-actions no-color">
							<input type="submit" value="Delete" class="btn btn-default" /> |
							<a asp-action="Index">Back to List</a>
						</div>
					</form>   
				</div>

			</div>
		</div>
	</div>
</div>
<!-- END .content-wrapper -->

src/Fugitive4.Web/Views/AKA/Details.cshtml
@model Fugitive4.Web.ViewModels.AKA.AKAVm

@{
    ViewBag.Title = "AKA Detail";
}
<div class="content-wrapper">
	<div class="panel panel-default">
		<div class="panel-body">
			<div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id"/>
			<div class="row">
				<div class="col-md-6">
			        <div class="pull-right">
                        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
			        </div>
								<div class="form-group">
									<label asp-for="Firstname" class="col-md-2 control-label"></label>
									@Html.DisplayFor(model => model.Firstname)
					
					</div>
								<div class="form-group">
									<label asp-for="Middlename" class="col-md-2 control-label"></label>
									@Html.DisplayFor(model => model.Middlename)
					
					</div>
								<div class="form-group">
									<label asp-for="Lastname" class="col-md-2 control-label"></label>
									@Html.DisplayFor(model => model.Lastname)
					
					</div>
								<div class="form-group">
									<label asp-for="SubjectId" class="col-md-2 control-label"></label>
									<div class="col-md-10">
							@Html.DisplayFor(model => model.SubjectId)
						</div>
					
					</div>
								<div class="form-group">
				
						@Html.DisplayFor(model => model.Disabled)
						<label asp-for="Disabled" class="col-md-2 control-label"></label>
					
					</div>
						
				</div>
				<!-- END .col -->
			</div>
			<!-- END .row -->

		</div>
	</div>
</div>
<!-- END .content-wrapper -->
   

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript">
        (function () {
            $("a.glyphicon-info-sign").tooltip();
        })();
    </script>
}

src/Fugitive4.Web/Views/AKA/Edit.cshtml
@model Fugitive4.Web.ViewModels.AKA.AKAVm

@{
    ViewBag.Title = "Edit AKA";
}

<form asp-action="Edit" asp-route-returnUrl="@ViewBag.ReturnUrl">     
	<div class="form-horizontal">
		<div class="row title-row">
			<h1 class="pull-left">@ViewBag.Title</h1>

			<div class="button-container pull-right h1-row text-right">
				<a asp-controller="AKA" asp-action="Index">Cancel</a>
				<input type="submit" value="Edit" class="btn btn-default" />
			</div>
		</div>

<div class="content-wrapper">
	<div class="panel panel-default">
		<div class="panel-body">
			<div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id"/>
				<div class="row">
					<div class="form-group col-md-12">
						<label asp-for="Firstname" class="control-label"></label>
						<input asp-for="Firstname" class="form-control"/>
					
						<span asp-validation-for="Firstname" class="text-danger" />
					</div>
				</div>
				<div class="row">
					<div class="form-group col-md-12">
						<label asp-for="Middlename" class="control-label"></label>
						<input asp-for="Middlename" class="form-control"/>
					
						<span asp-validation-for="Middlename" class="text-danger" />
					</div>
				</div>
				<div class="row">
					<div class="form-group col-md-12">
						<label asp-for="Lastname" class="control-label"></label>
						<input asp-for="Lastname" class="form-control"/>
					
						<span asp-validation-for="Lastname" class="text-danger" />
					</div>
				</div>
						<input type="hidden" asp-for="SubjectId" />
	<div class="row">
					<div class="form-group col-md-12">
						<label asp-for="SubjectId" class="control-label"></label>
					
						<span asp-validation-for="SubjectId" class="text-danger" />
					</div>
				</div>
				<div class="row">
					<div class="form-group col-md-12">
				
						<input asp-for="Disabled" class="form-control"/>
						<label asp-for="Disabled" class="control-label"></label>
					
						<span asp-validation-for="Disabled" class="text-danger" />
					</div>
				</div>
				
		</div>
	</div>
</div>
<!-- END .content-wrapper -->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
				<a asp-controller="AKA" asp-action="Index">Cancel</a>
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Fugitive4.Web/Views/AKA/Index.cshtml
@model Fugitive4.Web.ViewModels.AKA.AKAListVm

@{
    ViewBag.Title = "Manage AKA";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="panel panel-default">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>
					@Html.DisplayNameFor(model => model.AKAS.FirstOrDefault().Firstname)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.AKAS.FirstOrDefault().Middlename)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.AKAS.FirstOrDefault().Lastname)
				</th>

				<th></th>	
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.AKAS) 
			{
			<tr>

				<td>
					@Html.DisplayFor(modelItem => item.Firstname)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Middlename)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Lastname)
				</td>

       <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
			</tr>
			}
		</tbody>
	</table>
</div>

<div class=" footer-button-row">
	<div class="button-container text-right">
		@Html.ActionLink("Back to Subjects", "Index", "Subject", null, new {@class="pull-left"})
		<a asp-action="Create">Create New</a>
	</div>
</div>