src/Fugitive4.Web/Controllers/EmployerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using AutoMapper;
using Fugitive4.Web.Extensions;
using Fugitive4.Services.Models;
using Fugitive4.Services.Services;
using Fugitive4.Web.Controllers.Bases;
using Fugitive4.Web.ViewModels.Employer;
using Microsoft.AspNet.Authorization;

namespace Fugitive4.Web.Controllers
{
    [Authorize(Roles = "Member,Admin")]
    public class EmployerController : ControllerBase
    {
	    private readonly IMapper _mapper;
		private readonly IEmployerService _employerService;					
		private readonly ISubjectService _subjectService;

		public EmployerController(IEmployerService employerService,
								ISubjectService subjectService,
								IMapper mapper		)
        {
            _employerService = employerService;
			_mapper = mapper;
			_subjectService = subjectService;

        }
		[Route("Subject/{subjectId}/Employer/Index")]
        public async Task<IActionResult> Index(int subjectId , string searchCriteria = null)
        {
			ViewBag.Title = "Index";
			ViewBag.TestValue = "Index";

            var employers = await _employerService.GetAllAsync();
            var employerList = new EmployerListVm
            {
                Employers = _mapper.Map<IEnumerable<Employer>, IEnumerable<EmployerVm>>(employers.ToList())
            };

            return View("Index", employerList);
        }

		public async Task<IActionResult> Details(int? id)
        {
			ViewBag.TestValue = "Details";
            if (id == null)
            {
                return HttpNotFound();
            }

            Employer employer = await _employerService.GetByIdAsync(id.Value);
            if (employer == null)
            {
                return HttpNotFound();
            }

            var employerVm = _mapper.Map<Employer, EmployerVm>(employer);

            return View(employerVm);
        }


		[Route("Subject/{subjectId}/Employer/Create", Name="EmployerForSubject")]
		public ActionResult Create(int subjectId , string returnUrl = "")
        {
			ViewBag.Title = "Create"; 
			ViewBag.TestValue = "Create";
			ViewBag.ReturnUrl = returnUrl;

            var employerVm = new EmployerVm();

			LoadLookups(employerVm);

            return View(employerVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
		[Route("Subject/{subjectId}/Employer/Create", Name = "EmployerForSubject")]
        public async Task<IActionResult> Create(EmployerVm employerVm, string returnUrl = "")
        {
			ViewBag.ReturnUrl = returnUrl;
            try
            {
                if (ModelState.IsValid)
                {
                    var employer = _mapper.Map<EmployerVm, Employer>(employerVm);
                    await _employerService.InsertAsync(employer, GetLogonUser());
					return RedirectToIndexOrSubjectDetail(returnUrl);
                }
				else
				{
                    var message = string.Join(" | ", ModelState.Values
                        .SelectMany(v => v.Errors)
                        .Select(e => e.ErrorMessage));
                    throw new Exception(message);
                }               
            }
            catch(Exception ex)
            {
				LogError(ex);
				//Add any dropdown values back to the VM Here
				LoadLookups(employerVm);

                return View(employerVm);
            }
        }

		[Route("Subject/{subjectId}/Employer/Edit/{id}", Name = "EmployerForSubjectEdit")]
		public async Task<IActionResult> Edit(int subjectId , int? id, string returnUrl = "")
        {
			ViewBag.Title = "Edit"; 
			ViewBag.TestValue = "Edit";
			ViewBag.ReturnUrl = returnUrl;

			if (id == null)
            {
                return HttpNotFound();
            }

            var employer = await _employerService.GetByIdAsync(id.Value);
            if (employer == null)
            {
                return HttpNotFound();
            }            
			
			var employerVm = _mapper.Map<Employer, EmployerVm>(employer);

			LoadLookups(employerVm);

            return View(employerVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
		[Route("Subject/{subjectId}/Employer/Edit/{id}", Name = "EmployerForSubjectEdit")]
        public async Task<IActionResult> Edit(EmployerVm employerVm, string returnUrl = "")
        {
			ViewBag.ReturnUrl = returnUrl;
            try
            {
                if (ModelState.IsValid)
                {
                    var employer = _mapper.Map<EmployerVm, Employer>(employerVm); 
                    await _employerService.UpdateAsync(employer, GetLogonUser());
					return RedirectToIndexOrSubjectDetail(returnUrl);
                }
				else
				{
                    var message = string.Join(" | ", ModelState.Values
                        .SelectMany(v => v.Errors)
                        .Select(e => e.ErrorMessage));
                    throw new Exception(message);
                }                 
            }
            catch(Exception ex)
            {
				LogError(ex);
				//Add any dropdown values back to the VM Here
				LoadLookups(employerVm);

                return View(employerVm);
            }
        }

		[ActionName("Delete")]
		[Route("Subject/{subjectId}/Employer/Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
			ViewBag.Title = "Delete";
			ViewBag.TestValue = "Delete"; 

			if (id == null)
            {
                return HttpNotFound();
            }

            var employer = await _employerService.GetByIdAsync(id.Value);
			if (employer == null)
            {
                return HttpNotFound();
            }

            var employerVm = _mapper.Map<Employer, EmployerVm>(employer);

            return View(employerVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
		[Route("Subject/{subjectId}/Employer/Delete/{id}")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _employerService.DeleteAsync(id, GetLogonUser());
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

		private void LoadLookups(EmployerVm employerVm)
        {
			employerVm.SubjectList = _subjectService.GetAll(GetLogonUser()).ToSelectList(s => s.Id.ToString(), s => s.EyeColor).ToList();
		}

	}
}

src/Fugitive4.Web/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using AutoMapper;
using Fugitive4.Services.Enums;
using Fugitive4.Web.Extensions;
using Fugitive4.Services.Models;
using Fugitive4.Services.Services;
using Fugitive4.Web.Controllers.Bases;
using Fugitive4.Web.ViewModels.ActivityNote;
using Fugitive4.Web.ViewModels.BailBond;
using Fugitive4.Web.ViewModels.Subject;
using Microsoft.AspNet.Authorization;
using Fugitive4.Web.ViewModels.SubjectRelationship;
using Fugitive4.Web.ViewModels.Address;
using Fugitive4.Web.ViewModels.StoredFile;
using Fugitive4.Web.ViewModels._Interfaces;

namespace Fugitive4.Web.Controllers
{
    [Authorize(Roles = "Member,Admin")]
    public class SubjectController : ControllerBase
    {
	    private readonly IMapper _mapper; 

		private readonly ISubjectService _subjectService;					
		private readonly IReferrerService _referrerService;					
		private readonly IGenderService _genderService;					
		private readonly IRaceService _raceService;
	    private readonly ISubjectRelationshipService _subjectRelationshipService;
	    private readonly IRelationshipTypeService _relationshipTypeService;
	    private readonly IAddressService _addressService;
	    private readonly IStoredFileService _storedFileService;
	    private readonly IBookingChargeService _bookingChargeService;
	    private readonly IEmployerService _employerService;

	    public SubjectController(ISubjectService subjectService,
								IReferrerService referrerService,
								IGenderService genderService,
								IRaceService raceService,
                                ISubjectRelationshipService subjectRelationshipService,
                                IRelationshipTypeService relationshipTypeService,
                                IAddressService addressService,
                                IStoredFileService storedFileService,
                                IBookingChargeService bookingChargeService,
                                IEmployerService employerService,
								IMapper mapper		)
        {
            _subjectService = subjectService;
			_mapper = mapper;
			_referrerService = referrerService;
			_genderService = genderService;
			_raceService = raceService;
	        _subjectRelationshipService = subjectRelationshipService;
	        _relationshipTypeService = relationshipTypeService;
	        _addressService = addressService;
	        _storedFileService = storedFileService;
	        _bookingChargeService = bookingChargeService;
	        _employerService = employerService;
        }


        public async Task<IActionResult> Search()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search(SubjectSearchVm subjectSearchVm)
        {
            return RedirectToAction(actionName: "Index", routeValues: new { searchCriteria = subjectSearchVm.SearchCriteria });
        }

        [Route("Subject/Index", Name="SubjectIndex")]
        public async Task<IActionResult> Index( string searchCriteria = null, int? bailBondId = null, int? employerId = null)
        {
			ViewBag.Title = "Index";
			ViewBag.TestValue = "Index";

            var subjects = (await _subjectService.GetAllAsync(GetLogonUser())).ToList();


            if (!string.IsNullOrWhiteSpace(searchCriteria))
            {
                var search = searchCriteria.Split();
                var subjectFilter = subjects.Where(a => search.All(
                s => (a.Lastname ?? "").ToLower().Contains(s.ToLower()) ||
                (a.Firstname ?? "").ToLower().Contains(s.ToLower()) ||
                (a.Middlename ?? "").ToLower().Contains(s.ToLower())
                ));
                subjects = (subjectFilter == null ? new List<Subject>() : subjectFilter.ToList());
            }
            else if(bailBondId.HasValue && bailBondId.Value > 0)
            {
                subjects = subjects.Where(s => s.SubjectRelationships != null && s.SubjectRelationships.Any(sr => sr.BailBondId == bailBondId.Value)).ToList();
            }
            else if (employerId.HasValue && employerId.Value > 0)
            {
                subjects = subjects.Where(s => s.SubjectRelationships != null && s.SubjectRelationships.Any(sr => sr.EmployerId == employerId.Value)).ToList();
            }
            else
            {

                var newSubjects =
                    subjects
                        .Where(s => !s.BailBonds.Any())
                        .Where( s=> !s.SubjectRelationships.Any())
                        .Where(s=> !s.OtherSubjectRelationships.Any())
                        .ToList();


                subjects = subjects
                    .Where(s => 
                                (s.BailBonds.Any(b => b.DefaultDate >= DateTime.Now && (b.Done.HasValue == false || (b.Done.HasValue && b.Done.Value == false)))) 
                          )
                    .OrderBy(s=>s.BailBonds
                    .OrderBy(t => t.DefaultDate)
                    .First()
                    .DefaultDate)
                    .ToList();

                try
                {
                    if (newSubjects.Any())
                    {
                        subjects.AddRange(newSubjects.ToList());
                    }
                }
                catch (Exception ex)
                {
                    
                }

            }
            
            var subjectvms = _mapper.Map<IEnumerable<Subject>, IEnumerable<SubjectVm>>(subjects.ToList());
            foreach (var subject in subjectvms)
            {
                subject.CurrentBond = subject
                .BailBonds
                .OrderBy(t => t.DefaultDate)
                .FirstOrDefault(b => b.DefaultDate > DateTime.Now);
            }

            var subjectList = new SubjectListVm
            {
                Subjects = subjectvms
            };

            return View("Index", subjectList);
        }
        public async Task<IActionResult> Geomap(int? id)
        {
            //Add urls to each of the addresses and locations, to link to the item in the software
            if (id == null)
            {
                return HttpNotFound();
            }

            Subject subject = await _subjectService.GetByIdAllAsync(id.Value, GetLogonUser());
            if (subject == null)
            {
                return HttpNotFound();
            }

            var subjectRelationships = _subjectRelationshipService.GetBySubjectId(id.Value).ToList();

            var geoMapVm = new GeoMapVm
            {
                Addresses = new List<SubjectMapAddressVm>(),
                Locations = new List<SubjectMapLatLongVm>()
            };

            foreach (IAddress address in subject.Addresses)
            {
                var subjectMapAddressVm = new SubjectMapAddressVm();
                subjectMapAddressVm.Name = "Subject ";
                subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", address.Address1, address.City, address.State, address.Zipcode);
                subjectMapAddressVm.Icon = "house";
                geoMapVm.Addresses.Add(subjectMapAddressVm);
            }

            foreach (var subjectRelationship in subjectRelationships)
            {
                var otherPerson = subjectRelationship.Subject.Id == subject.Id ? subjectRelationship.RelatedSubject : subjectRelationship.Subject;
                foreach (IAddress address in otherPerson.Addresses)
                {
                    var subjectMapAddressVm = new SubjectMapAddressVm();
                    subjectMapAddressVm.Name =String.Format("Related Subject - {0},{1}", otherPerson.Lastname,otherPerson.Firstname);
                    subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", address.Address1, address.City, address.State, address.Zipcode);
                    subjectMapAddressVm.Icon = "friend";
                    geoMapVm.Addresses.Add(subjectMapAddressVm);
                }
            }

            foreach(var bailBond in subject.BailBonds)
            {
                foreach(var charge in bailBond.BookingCharges)
                {
                    IAddress chargeAddress = charge as IAddress;
                    var subjectMapAddressVm = new SubjectMapAddressVm();
                    subjectMapAddressVm.Name = String.Format("Bond - {0},{1}", charge.ChargeName, charge.CodeNumber);
                    subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", chargeAddress.Address1, chargeAddress.City, chargeAddress.State, chargeAddress.Zipcode);
                    subjectMapAddressVm.Icon = "handcuffs";
                    geoMapVm.Addresses.Add(subjectMapAddressVm);
                }
            }

            foreach(var employer in subject.Employers)
            {
                IAddress employerAddress = employer as IAddress;
                var subjectMapAddressVm = new SubjectMapAddressVm();
                subjectMapAddressVm.Name = String.Format("Employer - {0}", employer.Name);
                subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", employerAddress.Address1, employerAddress.City, employerAddress.State, employerAddress.Zipcode);
                subjectMapAddressVm.Icon = "office";
                geoMapVm.Addresses.Add(subjectMapAddressVm);
            }

            foreach (var location in subject.ActivityNotes)
            {
                var subjectMapLatLongVm = new SubjectMapLatLongVm();
                subjectMapLatLongVm.Name = "Activity Note" + location.ActivityDate.ToString("M/d/yy h:m tt");
                subjectMapLatLongVm.Latitude = location.Latitude;
                subjectMapLatLongVm.Longitude = location.Longitude;
                subjectMapLatLongVm.Icon = "car";

src/Fugitive4.Web/Views/Employer/Create.cshtml
@using Fugitive4.Web.Helpers;
@model Fugitive4.Web.ViewModels.Employer.EmployerVm

@{
    ViewBag.Title = "Create Employer";
}

<form asp-action="Create" asp-route-returnUrl="@ViewBag.ReturnUrl">    
	<div class="form-horizontal">
		<div class="row title-row">
			<h1 class="pull-left">@ViewBag.Title</h1>

			<div class="button-container pull-right h1-row text-right">
				<a asp-controller="Employer" asp-action="Index">Cancel</a>
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div> 

<div class="content-wrapper">
	<div class="panel panel-default">
		<div class="panel-body">
			<div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
		    <input type="hidden" asp-for="Id"/>
		    <input type="hidden" asp-for="Disabled"/>
            <input type="hidden" asp-for="SubjectId" />

				<div class="row">
					<div class="form-group col-md-6">
						<label asp-for="Name" class="control-label"></label>
						<input asp-for="Name" class="form-control"/>
					
						<span asp-validation-for="Name" class="text-danger" />
					</div>
					<div class="form-group col-md-6">
						<label asp-for="JobTitle" class="control-label"></label>
						<input asp-for="JobTitle" class="form-control"/>					
						<span asp-validation-for="JobTitle" class="text-danger" />
					</div>
				</div>
				<div class="row">
					<div class="form-group col-md-12">
						<label asp-for="PhoneNumber" class="control-label"></label>
						<input asp-for="PhoneNumber" class="form-control"/>
					
						<span asp-validation-for="PhoneNumber" class="text-danger" />
					</div>
				</div>
				<div class="row">
					<div class="form-group col-md-6">
						<label asp-for="Address1" class="control-label"></label>
						<input asp-for="Address1" class="form-control" style="min-width: 100%"/>					
						<span asp-validation-for="Address1" class="text-danger" />
					</div>
					<div class="form-group col-md-6">
						<label asp-for="Address2" class="control-label"></label>
						<input asp-for="Address2" class="form-control" style="min-width: 100%"/>					
						<span asp-validation-for="Address2" class="text-danger" />
					</div>
				</div>
				<div class="row">
					<div class="form-group col-md-4">
						<label asp-for="City" class="control-label"></label>
						<input asp-for="City" class="form-control"/>					
						<span asp-validation-for="City" class="text-danger" />
					</div>
					<div class="form-group col-md-4">
						<label asp-for="State" class="control-label"></label>
						<input asp-for="State" class="form-control"/>					
						<span asp-validation-for="State" class="text-danger" />
					</div>
					<div class="form-group col-md-4">
						<label asp-for="Zipcode" class="control-label"></label>
						<input asp-for="Zipcode" class="form-control"/>					
						<span asp-validation-for="Zipcode" class="text-danger" />
					</div>
				</div>

				<div class="row">
					<div class="form-group col-md-6">
						<label asp-for="StartDate" class="control-label"></label>
						<input asp-for="StartDate" class="form-control"/>
					
						<span asp-validation-for="StartDate" class="text-danger" />
					</div>
		        <div class="form-group col-md-6">
		            <label asp-for="EndDate" class="control-label"></label>
		            <input asp-for="EndDate" class="form-control"/>

		            <span asp-validation-for="EndDate" class="text-danger" />
		        </div>
		    </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label asp-for="Notes" class="control-label"></label>
                    <textarea rows="15" asp-for="Notes" class="form-control"></textarea>
                    <span asp-validation-for="Notes" class="text-danger" />
                </div>
            </div>
				
		</div>
	</div>
</div>
<!-- END .content-wrapper -->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
				<a href="@LinkHelper.GetIndexOrReturnDetail(Context, ViewBag.ReturnUrl)">Cancel</a>
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script type="text/javascript">
        (function(){
            tinymce.init({ selector: '#Notes' });
        })();
    </script>
}

src/Fugitive4.Web/Views/Employer/Edit.cshtml
@model Fugitive4.Web.ViewModels.Employer.EmployerVm

@{
    ViewBag.Title = "Edit Employer";
}

<form asp-action="Edit" asp-route-returnUrl="@ViewBag.ReturnUrl">
    <div class="form-horizontal">
        <div class="row title-row">
            <h1 class="pull-left">@ViewBag.Title</h1>

            <div class="button-container pull-right h1-row text-right">
                <a asp-controller="Employer" asp-action="Index">Cancel</a>
                <input type="submit" value="Edit" class="btn btn-default"/>
            </div>
        </div>

        <div class="content-wrapper">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id"/>
                    <input type="hidden" asp-for="Disabled"/>
                    <input type="hidden" asp-for="SubjectId" />

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control"/>
                            <span asp-validation-for="Name" class="text-danger" />
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="JobTitle" class="control-label"></label>
                            <input asp-for="JobTitle" class="form-control"/>

                            <span asp-validation-for="JobTitle" class="text-danger" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label asp-for="PhoneNumber" class="control-label"></label>
                            <input asp-for="PhoneNumber" class="form-control"/>

                            <span asp-validation-for="PhoneNumber" class="text-danger" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="Address1" class="control-label"></label>
                            <input asp-for="Address1" class="form-control" style="min-width: 100%"/>

                            <span asp-validation-for="Address1" class="text-danger" />
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Address2" class="control-label"></label>
                            <input asp-for="Address2" class="form-control" style="min-width: 100%"/>

                            <span asp-validation-for="Address2" class="text-danger" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label asp-for="City" class="control-label"></label>
                            <input asp-for="City" class="form-control"/>

                            <span asp-validation-for="City" class="text-danger" />
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="State" class="control-label"></label>
                            <input asp-for="State" class="form-control"/>

                            <span asp-validation-for="State" class="text-danger" />
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="Zipcode" class="control-label"></label>
                            <input asp-for="Zipcode" class="form-control"/>

                            <span asp-validation-for="Zipcode" class="text-danger" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="StartDate" class="control-label"></label>
                            <input asp-for="StartDate" class="form-control"/>

                            <span asp-validation-for="StartDate" class="text-danger" />
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="EndDate" class="control-label"></label>
                            <input asp-for="EndDate" class="form-control"/>

                            <span asp-validation-for="EndDate" class="text-danger" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label asp-for="Notes" class="control-label"></label>
                            <textarea rows="15" asp-for="Notes" class="form-control"></textarea>
                            <span asp-validation-for="Notes" class="text-danger" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END .content-wrapper -->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a asp-controller="Employer" asp-action="Index">Cancel</a>
                <input type="submit" value="Edit" class="btn btn-default"/>
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-controller="SubjectRelationship"
       asp-action="Index"
       asp-route-employerid="@Model.Id">
        View SubjectRelationships
    </a>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script type="text/javascript">
        (function(){
            tinymce.init({ selector: '#Notes' });
        })();
    </script>
}

src/Fugitive4.Web/Views/Employer/Index.cshtml
@model Fugitive4.Web.ViewModels.Employer.EmployerListVm

@{
    ViewBag.Title = "Manage Employer";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="panel panel-default">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().Name)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().JobTitle)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().PhoneNumber)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().Address1)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().Address2)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().City)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().State)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().Zipcode)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().Notes)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().StartDate)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Employers.FirstOrDefault().EndDate)
				</th>

				<th></th>	
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.Employers) 
			{
			<tr>

				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.JobTitle)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.PhoneNumber)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Address1)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Address2)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.City)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.State)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Zipcode)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Notes)
				</td>
				<td>
					@(item.StartDate.HasValue ? item.StartDate.Value.ToString("M/d/yy") : "")
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.EndDate)
				</td>

       <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
			</tr>
			}
		</tbody>
	</table>
</div>

<div class=" footer-button-row">
	<div class="button-container text-right">
		@Html.ActionLink("Back to Subjects", "Index", "Subject", null, new {@class="pull-left"})
		<a asp-action="Create">Create New</a>
	</div>
</div>