src/Fugitive4.Web/ViewModels/Gender/GenderVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Mvc.Rendering;
using Fugitive4.Services.Models.Bases;
using Fugitive4.Web.ViewModels.Subject; //This is any parent or child vm

namespace Fugitive4.Web.ViewModels.Gender
{
	public class GenderVm : AuditableEntityBase
    {
		
		[Display(Name="Id")]	
		public int Id { get; set; }

		[Required]
		[StringLength(50, MinimumLength = 2, ErrorMessage = "field must be between 2 and 50 characters")]		
		[Display(Name="Name")]	
		public string Name { get; set; }


		public IEnumerable<SubjectVm> Subjects { get; set; }//Child
    }

    public class GenderListVm
    {
        public IEnumerable<GenderVm> Genders { get; set; }
		    }
}

src/Fugitive4.Web/Controllers/GenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using AutoMapper;
using Fugitive4.Web.Extensions;
using Fugitive4.Services.Models;
using Fugitive4.Services.Services;
using Fugitive4.Web.Controllers.Bases;
using Fugitive4.Web.ViewModels.Gender;
using Microsoft.AspNet.Authorization;

namespace Fugitive4.Web.Controllers
{
    [Authorize(Roles = "Member,Admin")]
    public class GenderController : ControllerBase
    {
	    private readonly IMapper _mapper;
		private readonly IGenderService _genderService;

		public GenderController(IGenderService genderService,
								IMapper mapper		)
        {
            _genderService = genderService;
			_mapper = mapper;

        }
        public async Task<IActionResult> Index( string searchCriteria = null)
        {
			ViewBag.Title = "Index";
			ViewBag.TestValue = "Index";

            var genders = await _genderService.GetAllAsync();
            var genderList = new GenderListVm
            {
                Genders = _mapper.Map<IEnumerable<Gender>, IEnumerable<GenderVm>>(genders.ToList())
            };

            return View("Index", genderList);
        }

		public async Task<IActionResult> Details(int? id)
        {
			ViewBag.TestValue = "Details";
            if (id == null)
            {
                return HttpNotFound();
            }

            Gender gender = await _genderService.GetByIdAsync(id.Value);
            if (gender == null)
            {
                return HttpNotFound();
            }

            var genderVm = _mapper.Map<Gender, GenderVm>(gender);

            return View(genderVm);
        }


		public ActionResult Create()
        {
			ViewBag.Title = "Create"; 
			ViewBag.TestValue = "Create";

            var genderVm = new GenderVm();

			LoadLookups(genderVm);

            return View(genderVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GenderVm genderVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var gender = _mapper.Map<GenderVm, Gender>(genderVm);
                    await _genderService.InsertAsync(gender, GetLogonUser());
					return RedirectToAction("Index");
                }
				else
				{
                    var message = string.Join(" | ", ModelState.Values
                        .SelectMany(v => v.Errors)
                        .Select(e => e.ErrorMessage));
                    throw new Exception(message);
                }               
            }
            catch(Exception ex)
            {
				LogError(ex);
				//Add any dropdown values back to the VM Here
				LoadLookups(genderVm);

                return View(genderVm);
            }
        }

		public async Task<IActionResult> Edit( int? id)
        {
			ViewBag.Title = "Edit"; 
			ViewBag.TestValue = "Edit";

			if (id == null)
            {
                return HttpNotFound();
            }

            var gender = await _genderService.GetByIdAsync(id.Value);
            if (gender == null)
            {
                return HttpNotFound();
            }            
			
			var genderVm = _mapper.Map<Gender, GenderVm>(gender);

			LoadLookups(genderVm);

            return View(genderVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(GenderVm genderVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var gender = _mapper.Map<GenderVm, Gender>(genderVm); 
                    await _genderService.UpdateAsync(gender, GetLogonUser());
					return RedirectToAction("Index");
                }
				else
				{
                    var message = string.Join(" | ", ModelState.Values
                        .SelectMany(v => v.Errors)
                        .Select(e => e.ErrorMessage));
                    throw new Exception(message);
                }                 
            }
            catch(Exception ex)
            {
				LogError(ex);
				//Add any dropdown values back to the VM Here
				LoadLookups(genderVm);

                return View(genderVm);
            }
        }

		[ActionName("Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
			ViewBag.Title = "Delete";
			ViewBag.TestValue = "Delete"; 

			if (id == null)
            {
                return HttpNotFound();
            }

            var gender = await _genderService.GetByIdAsync(id.Value);
			if (gender == null)
            {
                return HttpNotFound();
            }

            var genderVm = _mapper.Map<Gender, GenderVm>(gender);

            return View(genderVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _genderService.DeleteAsync(id, GetLogonUser());
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

		private void LoadLookups(GenderVm genderVm)
        {
		}

	}
}

src/Fugitive4.Web/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using AutoMapper;
using Fugitive4.Services.Enums;
using Fugitive4.Web.Extensions;
using Fugitive4.Services.Models;
using Fugitive4.Services.Services;
using Fugitive4.Web.Controllers.Bases;
using Fugitive4.Web.ViewModels.ActivityNote;
using Fugitive4.Web.ViewModels.BailBond;
using Fugitive4.Web.ViewModels.Subject;
using Microsoft.AspNet.Authorization;
using Fugitive4.Web.ViewModels.SubjectRelationship;
using Fugitive4.Web.ViewModels.Address;
using Fugitive4.Web.ViewModels.StoredFile;
using Fugitive4.Web.ViewModels._Interfaces;

namespace Fugitive4.Web.Controllers
{
    [Authorize(Roles = "Member,Admin")]
    public class SubjectController : ControllerBase
    {
	    private readonly IMapper _mapper; 

		private readonly ISubjectService _subjectService;					
		private readonly IReferrerService _referrerService;					
		private readonly IGenderService _genderService;					
		private readonly IRaceService _raceService;
	    private readonly ISubjectRelationshipService _subjectRelationshipService;
	    private readonly IRelationshipTypeService _relationshipTypeService;
	    private readonly IAddressService _addressService;
	    private readonly IStoredFileService _storedFileService;
	    private readonly IBookingChargeService _bookingChargeService;
	    private readonly IEmployerService _employerService;

	    public SubjectController(ISubjectService subjectService,
								IReferrerService referrerService,
								IGenderService genderService,
								IRaceService raceService,
                                ISubjectRelationshipService subjectRelationshipService,
                                IRelationshipTypeService relationshipTypeService,
                                IAddressService addressService,
                                IStoredFileService storedFileService,
                                IBookingChargeService bookingChargeService,
                                IEmployerService employerService,
								IMapper mapper		)
        {
            _subjectService = subjectService;
			_mapper = mapper;
			_referrerService = referrerService;
			_genderService = genderService;
			_raceService = raceService;
	        _subjectRelationshipService = subjectRelationshipService;
	        _relationshipTypeService = relationshipTypeService;
	        _addressService = addressService;
	        _storedFileService = storedFileService;
	        _bookingChargeService = bookingChargeService;
	        _employerService = employerService;
        }


        public async Task<IActionResult> Search()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search(SubjectSearchVm subjectSearchVm)
        {
            return RedirectToAction(actionName: "Index", routeValues: new { searchCriteria = subjectSearchVm.SearchCriteria });
        }

        [Route("Subject/Index", Name="SubjectIndex")]
        public async Task<IActionResult> Index( string searchCriteria = null, int? bailBondId = null, int? employerId = null)
        {
			ViewBag.Title = "Index";
			ViewBag.TestValue = "Index";

            var subjects = (await _subjectService.GetAllAsync(GetLogonUser())).ToList();


            if (!string.IsNullOrWhiteSpace(searchCriteria))
            {
                var search = searchCriteria.Split();
                var subjectFilter = subjects.Where(a => search.All(
                s => (a.Lastname ?? "").ToLower().Contains(s.ToLower()) ||
                (a.Firstname ?? "").ToLower().Contains(s.ToLower()) ||
                (a.Middlename ?? "").ToLower().Contains(s.ToLower())
                ));
                subjects = (subjectFilter == null ? new List<Subject>() : subjectFilter.ToList());
            }
            else if(bailBondId.HasValue && bailBondId.Value > 0)
            {
                subjects = subjects.Where(s => s.SubjectRelationships != null && s.SubjectRelationships.Any(sr => sr.BailBondId == bailBondId.Value)).ToList();
            }
            else if (employerId.HasValue && employerId.Value > 0)
            {
                subjects = subjects.Where(s => s.SubjectRelationships != null && s.SubjectRelationships.Any(sr => sr.EmployerId == employerId.Value)).ToList();
            }
            else
            {

                var newSubjects =
                    subjects
                        .Where(s => !s.BailBonds.Any())
                        .Where( s=> !s.SubjectRelationships.Any())
                        .Where(s=> !s.OtherSubjectRelationships.Any())
                        .ToList();


                subjects = subjects
                    .Where(s => 
                                (s.BailBonds.Any(b => b.DefaultDate >= DateTime.Now && (b.Done.HasValue == false || (b.Done.HasValue && b.Done.Value == false)))) 
                          )
                    .OrderBy(s=>s.BailBonds
                    .OrderBy(t => t.DefaultDate)
                    .First()
                    .DefaultDate)
                    .ToList();

                try
                {
                    if (newSubjects.Any())
                    {
                        subjects.AddRange(newSubjects.ToList());
                    }
                }
                catch (Exception ex)
                {
                    
                }

            }
            
            var subjectvms = _mapper.Map<IEnumerable<Subject>, IEnumerable<SubjectVm>>(subjects.ToList());
            foreach (var subject in subjectvms)
            {
                subject.CurrentBond = subject
                .BailBonds
                .OrderBy(t => t.DefaultDate)
                .FirstOrDefault(b => b.DefaultDate > DateTime.Now);
            }

            var subjectList = new SubjectListVm
            {
                Subjects = subjectvms
            };

            return View("Index", subjectList);
        }
        public async Task<IActionResult> Geomap(int? id)
        {
            //Add urls to each of the addresses and locations, to link to the item in the software
            if (id == null)
            {
                return HttpNotFound();
            }

            Subject subject = await _subjectService.GetByIdAllAsync(id.Value, GetLogonUser());
            if (subject == null)
            {
                return HttpNotFound();
            }

            var subjectRelationships = _subjectRelationshipService.GetBySubjectId(id.Value).ToList();

            var geoMapVm = new GeoMapVm
            {
                Addresses = new List<SubjectMapAddressVm>(),
                Locations = new List<SubjectMapLatLongVm>()
            };

            foreach (IAddress address in subject.Addresses)
            {
                var subjectMapAddressVm = new SubjectMapAddressVm();
                subjectMapAddressVm.Name = "Subject ";
                subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", address.Address1, address.City, address.State, address.Zipcode);
                subjectMapAddressVm.Icon = "house";
                geoMapVm.Addresses.Add(subjectMapAddressVm);
            }

            foreach (var subjectRelationship in subjectRelationships)
            {
                var otherPerson = subjectRelationship.Subject.Id == subject.Id ? subjectRelationship.RelatedSubject : subjectRelationship.Subject;
                foreach (IAddress address in otherPerson.Addresses)
                {
                    var subjectMapAddressVm = new SubjectMapAddressVm();
                    subjectMapAddressVm.Name =String.Format("Related Subject - {0},{1}", otherPerson.Lastname,otherPerson.Firstname);
                    subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", address.Address1, address.City, address.State, address.Zipcode);
                    subjectMapAddressVm.Icon = "friend";
                    geoMapVm.Addresses.Add(subjectMapAddressVm);
                }
            }

            foreach(var bailBond in subject.BailBonds)
            {
                foreach(var charge in bailBond.BookingCharges)
                {
                    IAddress chargeAddress = charge as IAddress;
                    var subjectMapAddressVm = new SubjectMapAddressVm();
                    subjectMapAddressVm.Name = String.Format("Bond - {0},{1}", charge.ChargeName, charge.CodeNumber);
                    subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", chargeAddress.Address1, chargeAddress.City, chargeAddress.State, chargeAddress.Zipcode);
                    subjectMapAddressVm.Icon = "handcuffs";
                    geoMapVm.Addresses.Add(subjectMapAddressVm);
                }
            }

            foreach(var employer in subject.Employers)
            {
                IAddress employerAddress = employer as IAddress;
                var subjectMapAddressVm = new SubjectMapAddressVm();
                subjectMapAddressVm.Name = String.Format("Employer - {0}", employer.Name);
                subjectMapAddressVm.Address = string.Format("{0},{1} {2} {3}", employerAddress.Address1, employerAddress.City, employerAddress.State, employerAddress.Zipcode);
                subjectMapAddressVm.Icon = "office";
                geoMapVm.Addresses.Add(subjectMapAddressVm);
            }

            foreach (var location in subject.ActivityNotes)
            {
                var subjectMapLatLongVm = new SubjectMapLatLongVm();
                subjectMapLatLongVm.Name = "Activity Note" + location.ActivityDate.ToString("M/d/yy h:m tt");
                subjectMapLatLongVm.Latitude = location.Latitude;
                subjectMapLatLongVm.Longitude = location.Longitude;
                subjectMapLatLongVm.Icon = "car";

src/Fugitive4.Web/Views/Gender/Create.cshtml
@model Fugitive4.Web.ViewModels.Gender.GenderVm

@{
    ViewBag.Title = "Create Gender";
}

<form asp-action="Create">    
	<div class="form-horizontal">
		<div class="row title-row">
			<h1 class="pull-left">@ViewBag.Title</h1>

			<div class="button-container pull-right h1-row text-right">
				<a asp-controller="Gender" asp-action="Index">Cancel</a>
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>

<div class="content-wrapper">
	<div class="panel panel-default">
		<div class="panel-body">
			<div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id"/>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label asp-for="Name" class="col-md-2 control-label"></label>
						<input asp-for="Name" class="form-control"/>
			<span asp-validation-for="Name" class="text-danger" />
					
						<span asp-validation-for="Name" class="text-danger" />
					</div>
						
				</div>
				<!-- END .col -->
			</div>
			<!-- END .row -->

		</div>
	</div>
</div>
<!-- END .content-wrapper -->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
				<a asp-controller="Gender" asp-action="Index">Cancel</a>
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Fugitive4.Web/Views/Gender/Delete.cshtml
@model Fugitive4.Web.ViewModels.Gender.GenderVm

@{
    ViewBag.Title = "Delete Gender";
}


<div class="row title-row">
	<h1 class="pull-left">@ViewBag.Title</h1>

	<div class="button-container pull-right h1-row text-right">
		<form asp-action="Delete">
			<div class="form-actions no-color">
				<input type="submit" value="Delete" class="btn btn-default" /> |
				<a asp-action="Index">Back to List</a>
			</div>
		</form>
	</div>
</div>

<div class="content-wrapper">

	<div class="panel panel-default">
		<div class="panel-body">

			<div class="alert alert-danger clearfix">
				<p class="pull-left">Are you sure you want to delete this Gender?</p>
			</div>
			<!-- END .alert -->

			<div>
				<dl class="section-spacing clearfix dl-inline-dd dl-inline-label-right">
 
					<dt>@Html.DisplayNameFor(model => model.Name)</dt>
					<dd>@Html.DisplayFor(model => model.Name)</dd>

				</dl>

				@Html.HiddenFor(model=>model.Id)
				@Html.HiddenFor(model=>model.Name)
				<div class="button-container top-hr text-right">    
					<form asp-action="Delete">
						<div class="form-actions no-color">
							<input type="submit" value="Delete" class="btn btn-default" /> |
							<a asp-action="Index">Back to List</a>
						</div>
					</form>   
				</div>

			</div>
		</div>
	</div>
</div>
<!-- END .content-wrapper -->

src/Fugitive4.Web/Views/Gender/Details.cshtml
@model Fugitive4.Web.ViewModels.Gender.GenderVm

@{
    ViewBag.Title = "Gender Detail";
}
<div class="content-wrapper">
	<div class="panel panel-default">
		<div class="panel-body">
			<div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id"/>
			<div class="row">
				<div class="col-md-6">
			        <div class="pull-right">
                        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
			        </div>
								<div class="form-group">
									<label asp-for="Name" class="col-md-2 control-label"></label>
									@Html.DisplayFor(model => model.Name)
					
					</div>
						
				</div>
				<!-- END .col -->
			</div>
			<!-- END .row -->

		</div>
	</div>
</div>
<!-- END .content-wrapper -->
   
<div>
    <a asp-controller="Subject"
       asp-action="Index"
       asp-route-genderid="@Model.Id">
        View Subjects
    </a>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Fugitive4.Web/Views/Gender/Edit.cshtml
@model Fugitive4.Web.ViewModels.Gender.GenderVm

@{
    ViewBag.Title = "Edit Gender";
}

<form asp-action="Edit" asp-route-returnUrl="@ViewBag.ReturnUrl">    
	<div class="form-horizontal">
		<div class="row title-row">
			<h1 class="pull-left">@ViewBag.Title</h1>

			<div class="button-container pull-right h1-row text-right">
				<a asp-controller="Gender" asp-action="Index">Cancel</a>
				<input type="submit" value="Edit" class="btn btn-default" />
			</div>
		</div>

<div class="content-wrapper">
	<div class="panel panel-default">
		<div class="panel-body">
			<div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id"/>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label asp-for="Name" class="col-md-2 control-label"></label>
						<input asp-for="Name" class="form-control"/>
			<span asp-validation-for="Name" class="text-danger" />
					
						<span asp-validation-for="Name" class="text-danger" />
					</div>
						
				</div>
				<!-- END .col -->
			</div>
			<!-- END .row -->

		</div>
	</div>
</div>
<!-- END .content-wrapper -->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
				<a asp-controller="Gender" asp-action="Index">Cancel</a>
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-controller="Subject"
       asp-action="Index"
       asp-route-genderid="@Model.Id">
        View Subjects
    </a>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Fugitive4.Web/Views/Gender/Index.cshtml
@model Fugitive4.Web.ViewModels.Gender.GenderListVm

@{
    ViewBag.Title = "Manage Gender";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="panel panel-default">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>
					@Html.DisplayNameFor(model => model.Genders.FirstOrDefault().Name)
				</th>

				<th></th>	
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.Genders) 
			{
			<tr>

				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>

       <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
			</tr>
			}
		</tbody>
	</table>
</div>

<div class=" footer-button-row">
	<div class="button-container text-right">
		@Html.ActionLink("Back to Subjects", "Index", "Subject", null, new {@class="pull-left"})
		<a asp-action="Create">Create New</a>
	</div>
</div>